### ISSUE TITLE
 Scraper for InterraTravel Fails to Display Jobs and Redirect to Company Page

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/scrapers_python_iurie#149]
**Environment:**
Production URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

**Steps to Reproduce:**
1. Open the URL https://admin.peviitor.ro/ in the browser.
2. Navigate to the "Cont" section.
3. Attempt to run the scraper for the company "InterraTravel.py".
4. Go to the "Companii" section and search for "InterraTravel".

**Expected Result:**
1. Job listings for InterraTravel should be displayed.
2. Clicking "Catre Website" should open the company's page.

**Actual Result:**
1. No job listings are displayed for InterraTravel.
2. Clicking "Catre Website" does not open the company's page; it refreshes the validator instead.

**Additional Details:**
Job listings are available on the InterraTravel careers website: https://www.interra.ro/angajari/.

**Attachments:**
Screenshots: 
![image](https://github.com/user-attachments/assets/9e84901c-7ea5-4547-b756-27f1822184cc)
![image](https://github.com/user-attachments/assets/e387f17b-1de3-415f-af8b-1193d5933251)

**Comment by IurieChi** [comment]
Jobs are scraped and added to the validator.
<img width="327" alt="Screenshot 2024-07-29 at 12 15 50" src="https://github.com/user-attachments/assets/d9133d47-edd0-4180-842f-c2fcc4e7eae1">

all 6 jobs are published in the production  
<img width="1279" alt="Screenshot 2024-07-29 at 12 12 51" src="https://github.com/user-attachments/assets/d639865a-46e1-4f60-9b51-698bb36e2726">

**Comment by IurieChi** [comment]
function Clicking "Catre Website" should open for interra is functional

**Comment by Catalinay** [comment]
retested, all works
