### ISSUE TITLE
Scraper Fails to Run for Company Deloitte

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/scrapers_python_iurie#159]
**Environment**:
Production URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

**Steps to Reproduce:**
1. Open the URL https://admin.peviitor.ro/ in the browser.
2. Navigate to the "Cont" section.
3. Attempt to run the scraper "deloitte.py".

**Expected Result:**
The scraper runs successfully.

**Actual Result:**
The scraper does not run.

**Attachments:**
![image](https://github.com/user-attachments/assets/44c6cdae-c138-4ca2-889d-f4025797b61f)

**Comment by IurieChi** [comment]
Issus fixed  
<img width="244" alt="Screenshot 2024-09-09 at 12 57 37" src="https://github.com/user-attachments/assets/634c5718-ffdc-4796-a272-5be4df84c0da">

**Comment by Catalinay** [comment]
retested, all works
