### ISSUE TITLE
 Scraper "simavi.py" Fails to Run

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/scrapers_python_iurie#163]
**Environment**:
Production URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

**Steps to Reproduce:**
1. Open the URL https://admin.peviitor.ro/ in the Chrome browser.
2. Navigate to the "Cont" section.
3. Attempt to run the scraper "simavi.py".

**Expected Result:**
The scraper "simavi.py" should run successfully.
**Actual Result:**
The scraper "simavi.py" does not run.

**Attachments:**
![image](https://github.com/user-attachments/assets/36a250fe-0917-4500-b524-11ac001fe5f2)

**Comment by IurieChi** [comment]
scraper run successfully in validator and locally 2 jobs available 
<img width="1220" alt="Screenshot 2024-08-05 at 12 02 13" src="https://github.com/user-attachments/assets/ab8fe50f-cd85-44a2-b439-ed6503ed167a">

<img width="570" alt="Screenshot 2024-08-05 at 12 00 42" src="https://github.com/user-attachments/assets/0fa2eb25-57b4-4ff7-bbf7-9bedb1ca0a93">

**Comment by IurieChi** [comment]
currently have no job openings
<img width="1256" alt="Screenshot 2024-09-11 at 10 52 56" src="https://github.com/user-attachments/assets/56da6e7a-81bf-4657-ba3f-a8062227f62f">
