### ISSUE TITLE
Also - Incorrect logo

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#17]
ENVIRONMENT: production
URL: https://firme.peviitor.ro
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE
1.Open URL in browser
2.Type "also"

EXPECTED RESULTS
The correct logo must appear.
<img width="191" alt="Screenshot 2024-03-10 at 19 29 30" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/20fc0db4-8ca0-454d-80fb-5a2ee07a9799">

ACTUAL RESULTS
An incorrect logo is displayed.
<img width="176" alt="Screenshot 2024-03-10 at 19 26 58" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/eba2d894-b900-48aa-9d65-890f843fb546">

**Comment by IurieChi** [comment]
The logo has been changed, issue. fixed

**Comment by claudiaelenarusu** [comment]
<img width="190" alt="Screenshot 2024-03-11 at 21 22 07" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/0165aa78-17d1-4698-988a-99b3fdb97ffa">

**Comment by IurieChi** [comment]
The logo has been changed, issue. fixed
<img width="1077" alt="Screenshot 2024-03-12 at 18 30 43" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/6afb59de-6282-48c0-9b2b-6997bcb13b59">
