### ISSUE TITLE
Engie - Two logos displayed

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#18]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE
1.Open URL in browser
2.Type in the search bar: "engie"

EXPECTED RESULTS
The logo company must be displayed just once.

ACTUAL RESULTS
Two companies with the same name are displayed.
[
<img width="737" alt="Screenshot 2024-03-10 at 19 32 33" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/df2e0ddb-d9b2-4c1f-9c8e-b9e2954916dd">
](url)

**Comment by IurieChi** [comment]
Duplicate logo cleared 
<img width="745" alt="Screenshot 2024-03-11 at 11 56 43" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/d2445571-6daf-4927-a464-35948bdbf78f">
