### ISSUE TITLE
Alight scraper not working

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/scrapers_python_iurie#184]
- URL: https://admin.peviitor.ro/ 
- Browser: Safari
- Device: iPhone 15  
- OS:iOS 17.6.1

### STEPS TO REPRODUCE: 
- Open the URL "https://admin.peviitor.ro/" in the browser 
- Insert "Alight" on search box, press enter 
- Click on Alight icon and check the chart 
- Click on "Cont" 
- Click on "+" from "scrapers_python_iurie"
- Click on "alight.py" and run the scraper  
### EXPECTED RESULTS: 
- The scraper should run without problem.
### ACTUAL RESULTS: 
- See below screenshot:![image](https://github.com/user-attachments/assets/57641d9e-8895-4ee1-aa87-c66a7acdcb57)

**Comment by IurieChi** [comment]
No available jobs for Romania

**Comment by lalalaurentiu** [comment]
My bad 😅
