### ISSUE TITLE
Engie - The city filter in the search bar display jobs in cities other than the one chosen

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#19]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Engie" in the search bar
3. Choose "Craiova" from the list in the city filter
4. Click "Cauta"

EXPECTED RESULT:
The jobs available in the selected city must be displayed on the screen.

ACTUAL RESULT:
Jobs from other cities are displayed.
<img width="1440" alt="Screenshot 2024-03-10 at 20 01 41" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/194c19ac-864b-44a3-a6f0-7f1bb13e3798">

**Comment by IurieChi** [comment]
This issue is connected with API, is in progress to be solved

**Comment by IurieChi** [comment]
bug fixed

**Comment by claudiaelenarusu** [comment]
The bug persists.
Jobs from other counties and cities are displayed even if the city and county selected is "Craiova, Dolj".
<img width="1418" alt="Screenshot 2024-03-23 at 18 07 11" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/56f81f14-ebb8-4433-b29b-57968213fa2d">

**Comment by IurieChi** [comment]
if job_type is  remote then don't show the city
if the city is not a county show only the city 
if the location is county then show only the county  and city all

**Comment by IurieChi** [comment]
will be fixed with new UI
