### ISSUE TITLE
"Simavi" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/scrapers_python_iurie#190]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Simavi"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since August 20.

![image](https://github.com/user-attachments/assets/6c4c048a-b27b-48c4-b8f1-e4af20e65df9)

**Comment by IurieChi** [comment]
currently have no job openings

<img width="1256" alt="Screenshot 2024-09-11 at 10 52 56" src="https://github.com/user-attachments/assets/16b261a7-a11a-42d0-bb68-26af32594c18">
