### ISSUE TITLE
"Quest Global" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/scrapers_python_iurie#191]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Quest Global"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since August 19.

![image](https://github.com/user-attachments/assets/2097b956-052d-49bb-887b-1738d2413867)

**Comment by IurieChi** [comment]
issue fixed 
<img width="1527" alt="Screenshot 2024-09-11 at 10 47 37" src="https://github.com/user-attachments/assets/406bb24a-b5cf-4faa-8e26-7df75d036fe1">

**Comment by Florin201092** [comment]
FIXED!
