### ISSUE TITLE
"Sowelo" company - an error pops up in production (404 File not found)

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/scrapers_python_iurie#195]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL https://admin.peviitor.ro/ in the browser.
2. Search for "Sowelo" company.
3. Validate one job.
4. Go to "www.peviitor.ro".
5. Click on "Cauta" button.
6. Search for "Sowelo" company.
7. Click on "Catre site"

**EXPECTED RESULTS:**
The scraper runs without issues and the link should redirect you to the job.

**ACTUAL RESULTS:**
An error pops up.

![image](https://github.com/user-attachments/assets/02ed69ed-4293-4291-8663-d9d7b2f2124a)

**Comment by IurieChi** [comment]
for Romania 1 job  available 
link is active
<img width="1650" alt="Screenshot 2024-09-12 at 13 08 40" src="https://github.com/user-attachments/assets/dcf5553e-b028-42ea-8ef9-5fea220e22d9">
<img width="841" alt="Screenshot 2024-09-12 at 13 08 20" src="https://github.com/user-attachments/assets/a030f558-52e7-433e-b2d6-86a866e3c735">

**Comment by Florin201092** [comment]
You have to acces the link in production: https://peviitor.ro/#/rezultate?page=1&company=Sowelo

Click on "Catre site"

**Comment by Florin201092** [comment]
FIXED!
