### ISSUE TITLE
"AD01" company - an error pops up in production (404 File not found)

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/scrapers_python_iurie#196]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL https://admin.peviitor.ro/ in the browser.
2. Search for "AD01" company.
3. Validate one job.
4. Go to "www.peviitor.ro".
5. Click on "Cauta" button.
6. Search for "AD01" company.
7. Click on "Catre site"

**EXPECTED RESULTS:**
The scraper runs without issues and the link should redirect you to the job.

**ACTUAL RESULTS:**
An error pops up.

![image](https://github.com/user-attachments/assets/d101b6b8-532c-409c-aa69-58d2b4ebd8f9)

**Comment by IurieChi** [comment]
15 jobs found 
links are active  if Click on "Catre site"
<img width="685" alt="Screenshot 2024-09-12 at 13 12 16" src="https://github.com/user-attachments/assets/e93a4a54-b555-4db2-b66c-a08f00006b51">

**Comment by Florin201092** [comment]
FIXED!
