### ISSUE TITLE
"Infotreeglobalsolutions" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/scrapers_python_iurie#201]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Infotreeglobalsolutions"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since August 20.

![image](https://github.com/user-attachments/assets/68e23ce7-47ad-4c6b-89c0-a1d58ded7ef8)

**Comment by IurieChi** [comment]
bug fixed 
<img width="787" alt="Screenshot 2024-09-16 at 19 51 35" src="https://github.com/user-attachments/assets/d3c2330b-d96b-4037-bd7d-dd4de70b84d0">

**Comment by Florin201092** [comment]
FIXED!
