### ISSUE TITLE
Encora Scraper Shows Jobs Outside of Romania

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/scrapers_python_iurie#209]
**Environment**: 
Production URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

**Steps to Reproduce:**
1. Open the URL https://admin.peviitor.ro/ in the browser.
2. Navigate to the "Account" section.
3. Attempt to run the scraper "encora.py" 
4. Check the jobs from Encora in the validator.

**Expected Result:**
Only jobs from Romania should be displayed.

**Actual Result:**
The validator shows jobs from outside Romania as well.

**Attachments:**
[DATA ANALYST
](https://careers.encora.com/application?4424375007&gh_jid=4424375007) 
![image](https://github.com/user-attachments/assets/065b3df9-184e-4b5b-8dcc-921796491ddd)

![image](https://github.com/user-attachments/assets/bb452b7e-0755-4609-b2ac-afc546c24c8d)

**Comment by IurieChi** [comment]
no available  jobs for Romania 
<img width="1418" alt="Screenshot 2024-09-19 at 10 26 23" src="https://github.com/user-attachments/assets/6ac42ca6-45ff-4620-a7b2-f4ac65753d99">

In validator all jobs cleaned 
<img width="266" alt="Screenshot 2024-09-19 at 10 31 44" src="https://github.com/user-attachments/assets/0dd2e821-2030-459b-8b58-81b0798be724">

**Comment by Catalinay** [comment]
retested, all works
