### ISSUE TITLE
Company name displayed twice

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#21]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL 
2. Type "BRINEL"
3. Press enter

EXPECTED RESULTS:

The company's name and logo should appear just once.
![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/9961ecb2-768b-45c6-8d76-669b1f811340)

ACTUAL RESULTS:

Two companies with the same name are displayed (one of them without logo)

**Comment by IurieChi** [comment]
Fixed old logo deleted 
<img width="666" alt="Screenshot 2024-03-11 at 19 54 02" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/cc096e0a-8de9-4310-b9cc-5ab571bb754a">
