### ISSUE TITLE
"Foundever" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/scrapers_python_iurie#211]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Foundever"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since August 21.

![image](https://github.com/user-attachments/assets/69acc042-58aa-4211-9fa9-9eec4840b481)

**Comment by IurieChi** [comment]
scraper run successfully
<img width="354" alt="Screenshot 2024-09-27 at 17 48 07" src="https://github.com/user-attachments/assets/e359f1b0-247f-4ee8-8f34-f0a5102b3508">
<img width="1496" alt="Screenshot 2024-09-27 at 17 48 20" src="https://github.com/user-attachments/assets/a98cea8a-d50d-49d0-8d88-8a7af20e92ca">

1 job available

**Comment by Florin201092** [comment]
Fixed!
