### ISSUE TITLE
Delgaz Grid no jobs

### ISSUE THREAD

**Issue by Myp456** [peviitor-ro/scrapers_python_iurie#217]
Steps to reproduce the bug

Open the URL  https://admin.peviitor.ro/  in the browser
Navigate to the "Account" section
Attempt to run the scrapper 
Check the jobs from validator
 
Expected result:  Have all jobs available on Delgaz page
Actual result: Had no jobs available on Delgaz page

Environment that was tested on

OS: Win 10
Browser: Edge, Chrome (last versions available for Win 10)
Device: PC

**Comment by IurieChi** [comment]
EON scraper need to be on hold to see if this is problem related with Delgaz

**Comment by IurieChi** [comment]
Bug fixed

**Comment by IurieChi** [comment]
<img width="305" alt="Screenshot 2024-12-10 at 16 48 19" src="https://github.com/user-attachments/assets/750bac30-314e-44fc-94ea-99e9d628e715">
