### ISSUE TITLE
Wrong Logo

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#22]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL
2. Type "BRINEL"
3. Press enter

EXPECTED RESULTS:

The right company logo should appear (colored in red).
![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/497b197f-b552-4910-b69e-922893a61846)

ACTUAL RESULTS:
![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/5c725e6e-45e4-4eb8-a5c6-d05ffa2b937f)

The logo appears in white, being hard to read.

**Comment by IurieChi** [comment]
Fixed new logo added 
<img width="967" alt="Screenshot 2024-03-11 at 19 56 44" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/8f8cb17f-008d-49ad-90f5-6896ab9a3701">
