### ISSUE TITLE
"Avantajplay" scraper is not working | Outdated jobs in production

### ISSUE THREAD

**Issue by RaduLutu** [peviitor-ro/scrapers_python_iurie#235]
URL: https://admin.peviitor.ro/
Browser: Microsoft Edge
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser.
Click on "Acasa".
Type in "Cauta aici" box : "Avantajplay" and search

EXPECTED RESULTS:
The "Avantajplay" file should appear.
ACTUAL RESULTS:
The "Avantajplay" file is not found.
![Screenshot 2024-11-14 165535](https://github.com/user-attachments/assets/41254160-6f86-4b20-9ff2-1ea9a7b93911)

**Comment by IurieChi** [comment]
https://github.com/peviitor-ro/scrapers_python_iurie/pull/234 

#234 by [IurieChi](https://github.com/peviitor-ro/scrapers_python_iurie/issues?q=is%3Apr+author%3AIurieChi) was merged 3 minutes ago

**Comment by IurieChi** [comment]
bug fixed 
<img width="240" alt="Screenshot 2024-11-19 at 10 48 50" src="https://github.com/user-attachments/assets/cf583c1b-93d7-47fd-8ccd-519b86312aa6">
