### ISSUE TITLE
EON ENERGIE ROMANIA scraper is not synchronizing

### ISSUE THREAD

**Issue by RaduLutu** [peviitor-ro/scrapers_python_iurie#239]
Environment:

Production URL: https://admin.peviitor.ro/
Browser: Microsoft Edge
Device: Desktop
OS: Windows 11 Pro N

Steps to Reproduce:

Open the URL https://admin.peviitor.ro/ in the browser.
Navigate to the "Company" section.
Search and open "EONENERGIEROMANIA" 
Validate jobs from "EONENERGIEROMANIA" file.
Go to "peviitor.ro".

Check the jobs from in the validator.
Expected Result:
The validated jobs will appear.

Actual Result:
The validated jobs will not appear.

**Comment by IurieChi** [comment]
Need to  investigate with the FrontEnd team 
<img width="1458" alt="Screenshot 2024-11-26 at 12 29 21" src="https://github.com/user-attachments/assets/e9bac25b-f0b2-4de9-992c-9f07fd03d933">
<img width="1261" alt="Screenshot 2024-11-26 at 12 29 05" src="https://github.com/user-attachments/assets/bb156f9d-928a-459a-87f3-d268e896ac25">

Jobs are published but on prod are not present

**Comment by IurieChi** [comment]
EON ENERGIE ROMANIA scraper fixed

**Comment by IurieChi** [comment]
<img width="503" alt="Screenshot 2024-12-09 at 20 13 35" src="https://github.com/user-attachments/assets/f0ec7836-23cd-4ea8-b1c0-6af440359c66">

**Comment by IurieChi** [comment]
![Uploading Screenshot 2024-12-09 at 20.15.44.png…]()

**Comment by IurieChi** [comment]
No new jobs on company page
