### ISSUE TITLE
City Filter

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#24]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Type "BRINEL" in the search bar
3. Choose "Bucuresti" in the city filter
4. Click "Cauta"

EXPECTED RESULT:
The jobs available in the selected city will be displayed.

ACTUAL RESULT:
Jobs from other cities are displayed.

<img width="738" alt="image" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/ed696ac4-961e-470e-9c22-d0523c50fabc">
<img width="356" alt="image" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/bf3cbba9-2a8c-4fbd-a17b-cd3ecd6f1d14">

**Comment by IurieChi** [comment]
This issue is connected with API, and is in progress to be solved

**Comment by IurieChi** [comment]
bug fixed
