### ISSUE TITLE
Scraper " Premierresearch " is not working

### ISSUE THREAD

**Issue by RaduLutu** [peviitor-ro/scrapers_python_iurie#247]
Environment:

Production URL: https://admin.peviitor.ro/
Browser: Microsoft Edge
Device: Desktop
OS: Windows 11 Pro N

Steps to Reproduce:

Open the URL https://admin.peviitor.ro/ in the browser.
Navigate to the "Scraperi" section.
Attempt to run the scraper " Premierresearch " from the " scrapers_python_iurie " File.

Expected Result:
The scraper is running 

Actual Result:
The validator shows " A aparut o eroare. " 
![Screenshot 2024-12-09 192831](https://github.com/user-attachments/assets/37e4fef2-d387-4a6b-9e68-5a6c836eba72)

**Comment by IurieChi** [comment]
bug fixed

**Comment by IurieChi** [comment]
<img width="622" alt="Screenshot 2024-12-09 at 19 46 01" src="https://github.com/user-attachments/assets/ad7a8182-653b-4883-b84c-06c6b9fa4a39">
<img width="238" alt="Screenshot 2024-12-09 at 19 44 45" src="https://github.com/user-attachments/assets/f61b5bef-6a59-47bb-8ed8-cf91f473037e">
