### ISSUE TITLE
Also - Scraper not found

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#25]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

**STEPS TO REPRODUCE:**
1. Open URL: https://scrapers.peviitor.ro in browser
2. Type "Also" in search bar

**EXPECTED RESULT:**
Also scraper must be displayed.

**ACTUAL RESULT:**
Also scraper is not displayed.
<img width="841" alt="Screenshot 2024-03-11 at 21 38 28" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/a2fda30d-b05d-4168-9152-d8580ace67ed">

**Comment by IurieChi** [comment]
This environment will not be used in the future

**Comment by IurieChi** [comment]
remove tag bug
