### ISSUE TITLE
"Grab" company - analytics not up-to-date

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/scrapers_python_iurie#259]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Click on "Scraperi".
3. Click on "scrapers_python_iurie".
4. Enter "Grab" in the search bar.
5. Select "grab.py".
6. Click on "Ruleaza".
7. Click on "Companii".
8. Sort by "Personale Alfabetic".
9. Click on Grab - Vizualizeaza joburi.
10. Check the Analytics date.

EXPECTED RESULTS:
The Analytics date is the current date.

ACTUAL RESULTS:
The Analytics date is December 3, 2024.

![image](https://github.com/user-attachments/assets/21f15546-3fad-4941-b63e-fdd04c6478f3)

**Comment by IurieChi** [comment]
No, available jobs for Romania
<img width="1238" alt="Screenshot 2024-12-31 at 18 29 35" src="https://github.com/user-attachments/assets/36316d76-2fc4-45af-8671-d2700d70f58b" />
