### ISSUE TITLE
Codezilla - Scraper doesn't run

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#26]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL: https://scrapers.peviitor.ro/ in browser
2. Type "codezilla" in the search bar
3. Click on "Codezilla" file 
4. Click on "Run Scraper" button

EXPECTED RESULT:
After clicking "Run Scraper" relevant data pertaining to the company "Codezilla" is retrieved without any errors.

ACTUAL RESULT:
After clicking "Run Scraper" the following error is observed with the message: "python3: can't open file '/root/scraper_Api/scraper_Api/scrapers/Scrapers_Job_PeViitor/sites/codezilla_scraper.py': [Errno 2] No such file or directory"
<img width="1097" alt="Screenshot 2024-03-11 at 21 43 31" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/ba359b62-3cd7-4359-82c0-1e971f383fd9">

**Comment by IurieChi** [comment]
This environment will not be used in the future
