### ISSUE TITLE
Engie - Scraper doesn't run

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#27]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:

Open URL: https://scrapers.peviitor.ro/ in browser
Type "codezilla" in the search bar
Click on "Codezilla" file
Click on "Run Scraper" button
EXPECTED RESULT:
After clicking "Run Scraper" relevant data pertaining to the company "Codezilla" is retrieved without any errors.

ACTUAL RESULT:
After clicking "Run Scraper" the following error is observed with the message: "python3: can't open file '/root/scraper_Api/scraper_Api/scrapers/Scrapers_Job_PeViitor/sites/engie_scraper.py': [Errno 2] No such file or directory"
<img width="1098" alt="Screenshot 2024-03-11 at 21 56 18" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/25bfd9f0-2175-40e3-8965-374680780a54">

**Comment by IurieChi** [comment]
This environment will not be used in the future
