### ISSUE TITLE
Engie - Job type discrepancies on peviitor.ro

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#29]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Engie" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: curl 'https://api.peviitor.ro/v3/search/?company=engie&country=Rom%C3%A2nia&page=1 
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Engie and on the peviitor.ro website.

ACTUAL RESULT:
Discrepancies are found in the job type information provided on our website: peviitor.ro. The job type for the job openings is incorrectly displayed as "remote" on our website, which does not accurately reflect the actual job type specified on the Engie official website.
<img width="1094" alt="Screenshot 2024-03-12 at 20 37 28" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/9637f978-1a30-495a-97b9-0dcc1487e4c6">
<img width="1180" alt="Screenshot 2024-03-12 at 20 41 57" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/6c09e66c-4033-42e6-92b9-ebdfa7c2295f">

**Comment by IurieChi** [comment]
fixed

**Comment by claudiaelenarusu** [comment]
Job type does not appear at all.
<img width="1428" alt="Screenshot 2024-03-18 at 19 31 01" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/4b986ba4-4444-4571-9ae6-6d6f8210a259">

**Comment by claudiaelenarusu** [comment]
rules:
- if job_type is remote then don't show the city
- if the location is not a county show only the city
- if the location is county then show only the county and city all
