### ISSUE TITLE
Also - Job type discrepancies on peviitor.ro

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#30]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Also" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: https://api.peviitor.ro/v3/search/?company=also&country=Rom%C3%A2nia&page=1
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Also and on the peviitor.ro website.

ACTUAL RESULT:
Discrepancies are found in the job type information provided on our website peviitor.ro displayed as "remote", which does not accurately reflect the actual job type specified on the Also official website.
<img width="1420" alt="Screenshot 2024-03-12 at 21 15 40" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/453f715a-2739-4d84-bf4a-fb5816694d3b">
<img width="1428" alt="Screenshot 2024-03-12 at 21 16 04" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/c78a9339-f4fc-4968-82f7-23ff4249cc07">

**Comment by claudiaelenarusu** [comment]
Job type is not displayed.
<img width="1440" alt="Screenshot 2024-03-18 at 19 41 18" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/570e98af-35f8-42d1-aa74-a7e10c34e403">

**Comment by IurieChi** [comment]
This is related to front end

**Comment by claudiaelenarusu** [comment]
rules:
- if job_type is remote then don't show the city
- if the location is not a county show only the city
- if the location is county then show only the county and city all
