### ISSUE TITLE
Zenitech - The job type is hybrid for the "Data Engineer" position

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#38]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Zenitech" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: "https://api.peviitor.ro/v3/search/?company=zenitech&country=Rom%C3%A2nia&page=1"
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Zenitech and on the peviitor.ro website.

ACTUAL RESULT:
The job type from the API response doesn't reflect the job type from the Zenitech website.
<img width="783" alt="Screenshot 2024-03-18 at 21 34 24" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/166c8463-4b97-4d26-b028-dfa0b100a642">
<img width="1093" alt="Screenshot 2024-03-18 at 21 36 49" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/a23e4737-4b53-4ba6-ade0-b8458cf04941">

**Comment by IurieChi** [comment]
bug fixed
