### ISSUE TITLE
Webasto - Logo not displayed

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#47]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE
1.Open URL in browser
2.Type "webasto"

EXPECTED RESULTS
The correct logo must appear.
<img width="1016" alt="Screenshot 2024-03-23 at 17 57 44" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/bb9dac89-ae3e-4aca-bc74-98c985e71ff0">

ACTUAL RESULTS
"Logo not found".
<img width="776" alt="Screenshot 2024-03-23 at 17 50 12" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/bc193c40-3471-4f93-8210-f4e44fe6bcae">

**Comment by IurieChi** [comment]
fixed 
<img width="1062" alt="Screenshot 2024-03-24 at 20 47 12" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/5feb8aa5-e68d-46d3-b9b7-c2182f1180ad">
