### ISSUE TITLE
Job Type (Accace Payroll Specialist)

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#54]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL: https://peviitor.ro/
2. Type "Accace"
3. Press enter
4. Check the job position: Payroll Specialist
5. Check the job type: 
<img width="250" alt="image" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/db8714e3-bc77-4b1f-a53d-a32efeb4e85f">

6. Press ''Vezi postul'' and check the job type on the website page

![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/d9ce2ccb-199f-451d-bd48-4b0415d82bb9)

EXPECTED RESULTS:

The job type in the search should correspond to the one from the website.

**Comment by IurieChi** [comment]
fixed 
<img width="603" alt="Screenshot 2024-04-09 at 17 31 50" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/be83cc1b-860c-4e13-86dc-d1a19c960c16">
