### ISSUE TITLE
Job Type (Accace Senior Internal Accountant)

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#55]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL: https://peviitor.ro/
2. Type "Accace"
3. Press enter
4. Check the job position: Senior Internal Accountant
5. Check the job type:
<img width="261" alt="image" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/2b58abc9-7ab9-4aac-bcff-1fded88760b6">

6. Press ''Vezi postul'' and check the job type on the website page

![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/71157a5b-0e01-4e40-a6a5-09be64246097)

EXPECTED RESULTS:

The job type in the search should correspond to the one from the website.

**Comment by IurieChi** [comment]
fixed
