### ISSUE TITLE
Job Type (Bluewiresoftware Infrastructure Engineer)

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#56]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL: https://peviitor.ro/
2. Type "Bluewiresoftware"
3. Press enter
4. Check the job position: Infrastructure Engineer
5. Check the job type:
 
<img width="239" alt="image" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/7a64ee02-34b1-4804-87c8-26bc4eb591f1">

6. Press ''Vezi postul'' and check the job type on the website page
![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/70eff6be-4280-4b83-a0d5-c5f4d4ccad82)

EXPECTED RESULTS:

The job type in the search should correspond to the one from the website.

**Comment by IurieChi** [comment]
bug fixed 
<img width="953" alt="Screenshot 2024-04-24 at 12 54 38" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/47999d7b-10cc-474e-86c3-9b30d72b52f4">
