### ISSUE TITLE
City Filter

### ISSUE THREAD

**Issue by MihaelaMad** [peviitor-ro/scrapers_python_iurie#57]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

1. Open the URL in the browser: peviitor.ro
2. Type "Bluewiresoftware" in the search bar
3. Choose "Targu Mures" in the city filter
4. Click "Cauta"

EXPECTED RESULT:
The jobs available in the selected city will be displayed.

ACTUAL RESULT:
Jobs from other cities are displayed.

![image](https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/87e78269-6045-4b76-94c6-63ce61dd5244)

<img width="386" alt="image" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/153110403/ee84fe1d-d17d-48bf-9dd2-67e397288ca5">

**Comment by IurieChi** [comment]
this is an issue with front end search

**Comment by IurieChi** [comment]
if job_type is  remote then don't show the city
if the city is not a county show only the city 
if the location is county then show only the county  and city all
