### ISSUE TITLE
Also - The job type is remote for the "MB Solutions Key Account Manager" position

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#58]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Also" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: https://api.peviitor.ro/v3/search/?company=also&country=Rom%C3%A2nia&page=1
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Also and on the peviitor.ro website.

ACTUAL RESULT:
The job type from the API response doesn't reflect the job type from the Also website: the job type is remote.
<img width="514" alt="Screenshot 2024-03-25 at 20 46 52" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/b9e9a3a3-50d0-44ad-a58b-eabe88234a35">
<img width="1101" alt="Screenshot 2024-03-25 at 20 45 51" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/a5c60d10-d645-48f1-8e99-024d5f18e4df">

**Comment by IurieChi** [comment]
Fixed 
 
<img width="683" alt="Screenshot 2024-05-22 at 12 15 07" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/b06f8856-e24d-4ba3-be72-3d53f4c19faa">

**Comment by IurieChi** [comment]
fixed
