### ISSUE TITLE
Engie - Wrong city spelling for the Tehnician Operational SSM position

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#61]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Engie" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: https://api.peviitor.ro/v3/search/?company=engie&country=Rom%C3%A2nia&page=3
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Engie and on the peviitor.ro website.

ACTUAL RESULT:
Ploiesti city is misspelled.
<img width="597" alt="Screenshot 2024-03-31 at 20 52 18" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/f0247f36-f7cf-4496-94eb-fe94666dd5fe">

**Comment by IurieChi** [comment]
fiex
