### ISSUE TITLE
AscentCore - Two logos displayed

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#69]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE
1.Open URL in browser
2.Type in the search bar: "AscentCore"

EXPECTED RESULTS
The logo company must be displayed just once.

ACTUAL RESULTS
Two companies with the same name, but different logos are displayed.
<img width="701" alt="Screenshot 2024-04-08 at 19 55 11" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/c4222260-4a6e-449f-8794-eb819c549d97">

**Comment by IurieChi** [comment]
fixed 
<img width="712" alt="Screenshot 2024-04-09 at 17 11 20" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/5e8e7afd-3f36-450a-976b-5a24ac556430">
