### ISSUE TITLE
AscentCore - Job titles missing

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#70]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "AscentCore" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: https://api.peviitor.ro/v3/search/?q=ascentcore&country=Rom%C3%A2nia&page=1
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of AscentCore and on the peviitor.ro website.

ACTUAL RESULT:
Job titles are missing.
<img width="751" alt="Screenshot 2024-04-08 at 20 00 30" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/ccf5a2cf-9e7e-48db-bb04-0f10a1d38f56">
<img width="889" alt="Screenshot 2024-04-08 at 20 01 14" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/28dfd160-2b8a-4ed3-af22-4c05ac4fecdb">

**Comment by IurieChi** [comment]
issue fixed 
![Screenshot 2024-04-10 at 18 03 16](https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/db3d0a63-0aa3-4d48-812e-a7f0b206182f)
