### ISSUE TITLE
Deloitte - discrepancy between the number of jobs available

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#71]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Deloitte" in the search bar
3. Click on "Cauta"

EXPECTED RESULT:
The number of jobs available must be the same as on the Deloitte official website.

ACTUAL RESULT:
Discrepancy between the number of jobs displayed on peviitor.ro website (109 jobs) and the total results on Deloitte website (106 jobs in Romania).
<img width="700" alt="Screenshot 2024-04-08 at 20 26 28" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/653106c1-4af9-45d7-a68d-c2831addfc02">
<img width="685" alt="Screenshot 2024-04-08 at 20 29 12" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/66ee55e8-26a4-4778-a6b0-1ba496b33580">

**Comment by IurieChi** [comment]
fixed 
<img width="585" alt="Screenshot 2024-04-24 at 13 05 00" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/496171e6-cfaf-4aa6-8b70-e2b7b7f8a1d7">
<img width="552" alt="Screenshot 2024-04-24 at 13 05 55" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/fafd6772-5b5c-489e-84c8-d137edd14961">
