### ISSUE TITLE
Chorus - job location incomplete for the "Electrician uzinare tablouri electrice" position

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#74]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Chorus" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: https://api.peviitor.ro/v3/search/?q=chorus&country=Rom%C3%A2nia&page=1
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Chorus and on the peviitor.ro website.

ACTUAL RESULT:
Job locations from the API response incomplete: Bucuresti is missing.

<img width="634" alt="2" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/528e9157-1f42-44c6-852c-7159087bf245">

<img width="442" alt="2b" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/aa262e38-def9-4201-be7d-5137d90d99ab">

**Comment by IurieChi** [comment]
fixed
