### ISSUE TITLE
Olinio - The job type is remote for the "Database Analyst" position

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#82]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Olinio" in the search bar
3. Click on "Cauta"
4. Right-click and select "Inspect"
5. Copy the Request cURL: https://api.peviitor.ro/v3/search/?q=olinio&country=Rom%C3%A2nia&page=1
6. Open Postman and create a new entry with GET request
7. Click on "Send"

EXPECTED RESULT:
The GET request should return a response with a status of 200 OK and information related to job openings retrieved from the API response should match the information related to job openings listed on the official website of Olinio and on the peviitor.ro website.

ACTUAL RESULT:
The job type from the API response doesn't reflect the job type from Olinio website: the job type is remote.
<img width="455" alt="Screenshot 2024-04-17 at 17 26 07" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/5b490761-eb60-4acc-baaa-a70f93870ff1">

<img width="658" alt="Screenshot 2024-04-17 at 17 26 34" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/8be17f1d-cbfe-47a8-955f-becff7efe11c">

**Comment by IurieChi** [comment]
bug fixed 
<img width="756" alt="Screenshot 2024-04-18 at 15 46 01" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/a40eb483-6105-4923-bb3b-245ad4db69f8">
