### ISSUE TITLE
Olinio - IT Specialist position missing

### ISSUE THREAD

**Issue by claudiaelenarusu** [peviitor-ro/scrapers_python_iurie#83]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Safari
Device: Laptop
OS: macOS 14 Sonoma

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Olinio" in the search bar
3. Click on "Cauta"

EXPECTED RESULT:
The number of jobs available must be the same as on Olinio official website.

ACTUAL RESULT:
Only 13 jobs are displayed on peviitor.ro website, but on Olinio website 14 open positions are available in Bucharest, Romania: IT SPECIALIST position is not displayed on peviitor.ro
https://careers.olinio.com.cy/jobs/3580494-it-specialist-romania
<img width="364" alt="Screenshot 2024-04-17 at 18 01 24" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/142620951/c23229c5-5ad1-41f4-a1b8-53121cb15341">

**Comment by IurieChi** [comment]
bug fixed 
![Uploading Screenshot 2024-04-18 at 15.37.27.png…]()

**Comment by IurieChi** [comment]
<img width="1283" alt="Screenshot 2024-04-18 at 15 37 27" src="https://github.com/peviitor-ro/scrapers_python_iurie/assets/124267735/7edac650-2c86-49fc-a6a3-70f49e7d0e90">
